name: Docker 기반 Next.js 앱 배포

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:
    name: Docker 이미지 빌드 및 푸시
    runs-on: ubuntu-latest

    steps:
      - name: GitHub 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: Node 18 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 의존성 설치
        run: npm ci

      - name: Next.js 빌드
        run: npm run build

      - name: DockerHub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.IMAGE_NAME }}:latest

  deploy-to-server:
    name: 일반 서버에 배포
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: 서버에 SSH 접속 및 Docker 실행
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "📦 Docker 이미지 Pull"
            docker pull ${{ secrets.IMAGE_NAME }}:latest

            echo "🧹 기존 컨테이너 정리"
            docker stop app || true
            docker rm app || true

            echo "🚀 새 컨테이너 실행"
            docker run -d -p 80:3000 \
              --env-file /home/swyp9/app/.env \
              --name app \
              ${{ secrets.IMAGE_NAME }}:latest
