name: Docker 기반 Next.js 앱 배포

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-push:
    name: Docker 이미지 빌드 및 푸시
    runs-on: ubuntu-latest

    steps:
      - name: GitHub 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: DockerHub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 빌드
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
            --build-arg NEXT_PUBLIC_KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }} \
            --build-arg NEXT_PUBLIC_KAKAO_BACKEND_URI=${{ secrets.KAKAO_BACKEND_URI }} \
            -t ${{ secrets.IMAGE_NAME }}:latest .

      - name: Docker 이미지 푸시
        run: docker push ${{ secrets.IMAGE_NAME }}:latest

  deploy-to-server:
    name: 일반 서버에 배포
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: 서버에 SSH 접속 및 docker-compose 배포 실행
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            echo "📦 기존 컨테이너 중지 및 삭제"
            docker compose -f /home/swyp9/docker-front-compose.yml down || true

            echo "🚀 최신 이미지 pull 및 배포"
            docker compose -f /home/swyp9/docker-front-compose.yml up -d --pull always --build
